# Generated by Django 4.0.4 on 2023-03-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_order_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.parts'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='category',
            field=models.CharField(choices=[('フリーザー', 'フリーザー'), ('ロボット', 'ロボット'), ('コンベア', 'コンベア')], max_length=200, null=True),
        ),
    ]
